# production Dockerfile
FROM mysql:8.0.21 AS todo_list_db_prod

WORKDIR /usr/src/database

ADD ./../todo_list_db.sql /docker-entrypoint-initdb.d/0_todo_list_db.sql

RUN chmod -R 775 /docker-entrypoint-initdb.d
